name: Deploy Decipher Website to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "NODE_ENV=production" > .env
          echo "NEXT_TELEMETRY_DISABLED=1" >> .env

      - name: Build Docker image
        run: docker build -t vaibhav805/website:latest .

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Docker Hub
        run: docker push vaibhav805/website:latest

      - name: Logout from Docker Hub
        run: docker logout

  deploy:
    needs: build
    runs-on: self-hosted
    
    steps:
      - name: Stop and remove old container
        run: |
          sudo docker stop decipher || true
          sudo docker rm decipher || true
        continue-on-error: true

      - name: Remove old image
        run: sudo docker rmi vaibhav805/website:latest || true
        continue-on-error: true

      - name: Pull latest image from Docker Hub
        run: sudo docker pull vaibhav805/website:latest

      - name: Run new Docker container
        run: |
          sudo docker run -d \
            --name decipher \
            --restart unless-stopped \
            -p 3000:3000 \
            -e NODE_ENV=production \
            vaibhav805/website:latest

      - name: Clean up unused Docker resources
        run: sudo docker system prune -af --volumes
        continue-on-error: true

      - name: Verify deployment
        run: |
          sleep 5
          curl -f http://localhost:3000 || echo "Warning: Container may not be ready yet"
